import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import disc from '../images/disc.jpg'
import { Footer, NavigationBar } from '../templates/bars'

const Home: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>Discgolf-Webpage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar />

      <main className='main'>
        <div className='grid'>
          <div className='card'>
            <div className='card-text'>
              <h2>What is discgolf</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </div>
          </div>


          <div className='card'>
            <div className='card-text'>
              <h2>History of the sport &rarr;</h2>

              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </div>
            <div className='card-image'>
              <Image src={disc} />
            </div>

          </div>
          <div className='card'>
            <div className='card-text'>
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </div>
          </div>
        </div>
      </main >

      <Footer />
    </div >
  )
}

export default Home
